services:
  - type: web
    name: mindhive-api
    env: python
    buildCommand: |
      apt-get update && apt-get install -y chromium-driver
      pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PYTHONPATH
        value: /opt/render/project/src